### ISSUE TITLE
スタイルの適用

### ISSUE THREAD

**Issue by aso-takahiro** [aso-takahiro/cms#2]
デフォルトのスタイルから変更する。

1.取り急ぎフリーテーマのBootstrap Starterを使用する。
2.今回はメインカラー変更やレスポンシブ対応（されてなければ）のみに留める。
3.もし現段階で明らかに不要な要素がある場合は削除。
4.必要な要素の追加は今回はしない。

**Comment by aso-takahiro** [comment]
[Free CMS.js Themes](https://chrisdiana.dev/cms.js-themes/)

**Comment by nkoh-aso** [comment]
branch: gh-pages で確認してください。
権限の問題で確認出来ないのでメインの方で確認。
権限見直し。

**Comment by aso-takahiro** [comment]
↑
権限の問題云々は、権限の問題でSettingsに入れず、Github Pagesのsourceが変更できないという事。

**Comment by aso-takahiro** [comment]
branch: gh-pages で確認できました。
権限は見直さないことにしました。

> 1.取り急ぎフリーテーマのBootstrap Starterを使用する。

・反映済み

> 2.今回はメインカラー変更やレスポンシブ対応（されてなければ）のみに留める。

・メインカラーの変更は一旦保留。記事など少し書いてからにする。
・レスポンシブ対応済み

> 3.もし現段階で明らかに不要な要素がある場合は削除。

・たぶんない

> 4.必要な要素の追加は今回はしない。

・検索機能が息をしていないので別タスクで修正予定 #5 

よって完了
