### ISSUE TITLE
日本語化

### ISSUE THREAD

**Issue by aso-takahiro** [aso-takahiro/cms#3]
日本語化

1.既存postの削除。
2.適当な日本語postをアップ。（今回は表示確認のため1つ）
3.既存pageの削除。
4.適当な日本語pageをアップ。（今回は表示確認のため1つ）
5.共通パーツの日本語化

**Comment by nkoh-aso** [comment]
日本語化した記事が反映されない問題

-> `config.js`の設定（branch）がmasterになっているのが原因ぽい

**Comment by nkoh-aso** [comment]
日本語記事が表示された！
https://aso-takahiro.github.io/cms/#/posts

> 5.共通パーツの日本語化
gnavはデザイン的に英語のままにします。

**Comment by nkoh-aso** [comment]
次はバグを治す。
#5
