### ISSUE TITLE
ヘッダー検索の有効化

### ISSUE THREAD

**Issue by aso-takahiro** [aso-takahiro/cms#5]
ヘッダーについている、検索エリアが息をしていない。

-> `config.js`を書き換えていないのが原因。

`cms.js-themes`の`bootstrap-starter`からソースをもらってくる。

**Comment by aso-takahiro** [comment]
[bootstrap-starter.html](https://github.com/chrisdiana/cms.js-themes/blob/master/templates/bootstrap-starter.html)
↑HTMLソースの最下部に`config.js`に該当する記述がある。

**Comment by nkoh-aso** [comment]
修正対応済み！
https://aso-takahiro.github.io/cms/#/posts

**Comment by nkoh-aso** [comment]
`config.js`については色々テストしたいが、一旦検索機能が動作したためタスクは終了とする。
#6 ここで記事を投稿してから必要な機能は追加していく。
