### ISSUE TITLE
layouts（data.postsの出力）の修正

### ISSUE THREAD

**Issue by nkoh-aso** [aso-takahiro/cms#7]
### 対象ファイル：post.html / post-list.html
1. postページのauthoerが静的に`Mark`になっているのを動的に書き換える。
2. authorのリンクを外す。（暫定対応）
3. dateを日本語表記（年/月/日）にする。
-> post-list.htmlも

**Comment by aso-takahiro** [comment]
3. は後回しにします。
記事がたまってきてから対応

**Comment by nkoh-aso** [comment]
#6
